const app=document.querySelector('#app'),video=document.querySelector('#camera'),canvas=document.querySelector('#stage'),ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});
const startBtn=document.querySelector('#startBtn'),cameraBtn=document.querySelector('#cameraBtn'),filterBtn=document.querySelector('#filterBtn'),debugBtn=document.querySelector('#debugBtn'),recBtn=document.querySelector('#recBtn'),filterName=document.querySelector('#filterName'),bootStatus=document.querySelector('#bootStatus'),statusText=document.querySelector('#statusText'),statusDot=document.querySelector('#statusDot'),fpsEl=document.querySelector('#fps'),hint=document.querySelector('#hint'),toast=document.querySelector('#toast'),recBadge=document.querySelector('#recBadge'),recTime=document.querySelector('#recTime');
const filterCanvas=document.createElement('canvas'),filterCtx=filterCanvas.getContext('2d',{alpha:false,desynchronized:true}),recordCanvas=document.createElement('canvas'),recordCtx=recordCanvas.getContext('2d',{alpha:false,desynchronized:true});
const PRESETS=[
{name:'THERMAL HOLO',css:'contrast(1.42) saturate(3.8) sepia(.28) hue-rotate(145deg) brightness(1.06)',a:'rgba(65,232,255,.96)',b:'rgba(255,93,220,.72)',g:'rgba(52,220,255,.92)',scan:1,grid:1,glitch:0},
{name:'XRAY GLITCH',css:'grayscale(1) invert(.94) contrast(1.48) brightness(1.08)',a:'rgba(218,245,255,.98)',b:'rgba(104,186,255,.72)',g:'rgba(158,220,255,.88)',scan:1,grid:0,glitch:1},
{name:'VOID NEON',css:'invert(.82) hue-rotate(188deg) saturate(2.6) contrast(1.32)',a:'rgba(154,93,255,.98)',b:'rgba(57,233,255,.76)',g:'rgba(100,92,255,.92)',scan:1,grid:0,glitch:0},
{name:'HOLOGRAM+',css:'grayscale(.16) sepia(.72) saturate(5.5) hue-rotate(126deg) contrast(1.2) brightness(1.08)',a:'rgba(68,235,255,.98)',b:'rgba(255,110,225,.68)',g:'rgba(66,225,255,.94)',scan:1,grid:1,glitch:0},
{name:'RAW SHIELD',css:'none',a:'rgba(126,241,255,.98)',b:'rgba(255,255,255,.55)',g:'rgba(105,233,255,.86)',scan:0,grid:0,glitch:0}];
const LINKS=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
let worker=null,modelReady=false,backend='…',stream=null,facing='user',running=false,debug=false,preset=0,toastTimer=null,frameId=null,framePending=false,lastSent=0,workerCost=35,session=0;
let result={landmarks:[]},lastSeen=0,lastTwo=-Infinity,mode=null,target=null,display=null,history=[],alpha=0,sideSign=0,flipVotes=0,lastTwoCorners=null;
let filterAt=0,raf=null,lastRender=performance.now(),fpsN=0,fpsAt=performance.now(),particles=[],particleAt=0;
let recorder=null,recordStream=null,chunks=[],recording=false,recordStarted=0,recordMime='',recordAt=0;
startBtn.disabled=true;app.dataset.facing=facing;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),add=(a,b)=>({x:a.x+b.x,y:a.y+b.y,z:0}),sub=(a,b)=>({x:a.x-b.x,y:a.y-b.y,z:0}),mul=(a,s)=>({x:a.x*s,y:a.y*s,z:0}),dot=(a,b)=>a.x*b.x+a.y*b.y,mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:0}),avg=a=>({x:a.reduce((s,p)=>s+p.x,0)/a.length,y:a.reduce((s,p)=>s+p.y,0)/a.length,z:0}),norm=(v,f={x:1,y:0,z:0})=>{const n=Math.hypot(v.x,v.y);return n>1e-5?{x:v.x/n,y:v.y/n,z:0}:{...f}},lerp=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:0});
function status(t,s='warn'){statusText.textContent=t;statusDot.className=s}function pop(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1600)}
function initWorker(){bootStatus.textContent='Menyiapkan tracking worker…';status('Memuat model');worker=new Worker('./tracking-worker-v5.js',{type:'module'});worker.onmessage=e=>{const m=e.data||{};if(m.type==='ready'){backend=m.backend||'?';modelReady=true;bootStatus.textContent=`Tracking siap · ${backend} worker · Portal V5`;status('Siap','ready');startBtn.disabled=false;return}if(m.type==='fatal'){bootStatus.textContent=`Tracking gagal: ${m.message||'unknown'}`;status('Model gagal','error');return}if(m.type!=='result'||m.session!==session)return;framePending=false;workerCost=m.cost||workerCost;updateFromResult({landmarks:m.landmarks||[]},performance.now())};worker.onerror=e=>{console.error(e);framePending=false;status('Worker error','error')};worker.postMessage({type:'init'})}
async function openCamera(){if(!modelReady)return pop('Model masih dimuat.');if(recording)stopRecording();stopLoops();session++;framePending=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:60,min:24,max:60}}});video.srcObject=stream;if(!video.videoWidth||!video.videoHeight)await new Promise(r=>video.addEventListener('loadedmetadata',r,{once:true}));await video.play();app.dataset.facing=facing;resize();reset();running=true;app.dataset.state='live';status('CARI TANGAN');hint.innerHTML='Buka <b>jempol + telunjuk</b>';hint.classList.add('visible');raf=requestAnimationFrame(render);startPump()}catch(e){console.error(e);bootStatus.textContent=!window.isSecureContext?'Kamera butuh HTTPS.':'Izin kamera gagal.';status('Kamera gagal','error');pop(!window.isSecureContext?'Buka lewat HTTPS.':'Izinkan kamera lalu coba lagi.')}}
function stopLoops(){running=false;if(raf!==null)cancelAnimationFrame(raf);raf=null;if(frameId!==null){if(video.cancelVideoFrameCallback)video.cancelVideoFrameCallback(frameId);else cancelAnimationFrame(frameId)}frameId=null}
function reset(){result={landmarks:[]};lastSeen=0;lastTwo=-Infinity;mode=null;target=null;display=null;history=[];alpha=0;sideSign=0;flipVotes=0;lastTwoCorners=null;particles=[];filterAt=0;lastSent=0;lastRender=performance.now();fpsN=0;fpsAt=performance.now()}
function resize(){const w=Math.max(1,innerWidth),h=Math.max(1,innerHeight);canvas.width=Math.round(w);canvas.height=Math.round(h);canvas.style.width=w+'px';canvas.style.height=h+'px';recordCanvas.width=canvas.width;recordCanvas.height=canvas.height;const vw=video.videoWidth||1280,vh=video.videoHeight||720,s=Math.min(1,420/Math.max(vw,vh));filterCanvas.width=Math.max(1,Math.round(vw*s));filterCanvas.height=Math.max(1,Math.round(vh*s))}
function cover(sw,sh,dw,dh){const s=Math.max(dw/sw,dh/sh),w=sw*s,h=sh*s;return{s,x:(dw-w)/2,y:(dh-h)/2,w,h}}
async function sendFrame(now){if(!running||framePending||!worker||video.readyState<2)return;const period=clamp(workerCost*.82+8,backend==='GPU'?30:42,backend==='GPU'?58:82);if(now-lastSent<period)return;framePending=true;lastSent=now;const ss=session;try{const vw=video.videoWidth||1280,vh=video.videoHeight||720,max=backend==='GPU'?576:512,s=Math.min(1,max/Math.max(vw,vh)),rw=Math.max(1,Math.round(vw*s)),rh=Math.max(1,Math.round(vh*s));const bitmap=await createImageBitmap(video,{resizeWidth:rw,resizeHeight:rh,resizeQuality:'low'});if(!running||ss!==session){bitmap.close?.();framePending=false;return}worker.postMessage({type:'frame',bitmap,timestamp:performance.now(),session:ss},[bitmap])}catch(e){framePending=false;console.warn(e)}}
function startPump(){const pump=now=>{if(!running)return;sendFrame(now);frameId=video.requestVideoFrameCallback?video.requestVideoFrameCallback(pump):requestAnimationFrame(pump)};frameId=video.requestVideoFrameCallback?video.requestVideoFrameCallback(pump):requestAnimationFrame(pump)}
function toScreen(l){const vw=video.videoWidth||1,vh=video.videoHeight||1,t=cover(vw,vh,canvas.width,canvas.height),x=facing==='user'?1-l.x:l.x;return{x:t.x+x*vw*t.s,y:t.y+l.y*vh*t.s,z:l.z||0}}
function geom(l){const p=i=>toScreen(l[i]),w=p(0),tm=p(2),ti=p(3),tt=p(4),im=p(5),ip=p(6),it=p(8),mm=p(9),mt=p(12),rm=p(13),rt=p(16),pm=p(17),pt=p(20),c=avg([w,im,mm,rm,pm]);return{l,w,tm,ti,tt,im,ip,it,mm,mt,rm,rt,pm,pt,c,cx:c.x}}
function area(p){let a=0;for(let i=0;i<p.length;i++){const j=(i+1)%p.length;a+=p[i].x*p[j].y-p[j].x*p[i].y}return Math.abs(a/2)}
function angleOrder(p){const c=avg(p);return[...p].sort((a,b)=>Math.atan2(a.y-c.y,a.x-c.x)-Math.atan2(b.y-c.y,b.x-c.x))}function orders(p){const o=[];for(const b of[p,[...p].reverse()])for(let k=0;k<p.length;k++)o.push(Array.from({length:p.length},(_,i)=>b[(k+i)%p.length]));return o}function align(p,ref){const q=angleOrder(p);if(!ref)return q.map(x=>({...x}));let best=null,bs=1e20;for(const v of orders(q)){let s=0;for(let i=0;i<v.length;i++)s+=dist(v[i],ref[i]);if(s<bs){bs=s;best=v}}return best.map(x=>({...x}))}
function twoHand(h){if(h.length<2)return null;const s=[...h].sort((a,b)=>a.cx-b.cx),L=s[0],R=s[1];if(dist(L.c,R.c)<70||dist(L.tt,L.it)<22||dist(R.tt,R.it)<22)return null;const q=align([L.tt,L.it,R.tt,R.it],lastTwoCorners);if(area(q)<1100)return null;lastTwoCorners=q.map(x=>({...x}));const c=avg(q),bow=Math.sqrt(area(q))*.055,n=[];for(let i=0;i<4;i++){const a=q[i],b=q[(i+1)%4],m=mid(a,b),out=norm(sub(m,c));n.push({...a},add(m,mul(out,bow)))}return{mode:'two',nodes:n}}
function chooseSide(h,c,n,len){const sec=avg([h.mt,h.rt,h.pt]),signed=dot(sub(sec,c),n),raw=signed>=0?1:-1;if(!sideSign){sideSign=raw;return raw}if(raw!==sideSign&&Math.abs(signed)>Math.max(20,len*.32)){if(++flipVotes>=4){sideSign=raw;flipVotes=0}}else flipVotes=0;return sideSign}
function oneHand(h){const p0={...h.tt},p1={...h.it},len=dist(p0,p1);if(len<28)return null;const c=mid(p0,p1),u=norm(sub(p1,p0)),baseN={x:-u.y,y:u.x,z:0},n=mul(baseN,chooseSide(h,c,baseN,len)),secTips=avg([h.mt,h.rt,h.pt]),secRoots=avg([h.mm,h.rm,h.pm]),sec= sub(secTips,secRoots),forward=Math.max(0,dot(sec,n)),spread=dist(h.mt,h.pt),depth=clamp(len*1.24+forward*.18+spread*.10,72,Math.min(canvas.width,canvas.height)*.43),side=clamp(dot(sub(secTips,c),u)*.15,-len*.18,len*.18),fc=add(add(c,mul(n,depth)),mul(u,side)),half=clamp(len*.50+spread*.10,len*.42,len*.65),fr=add(fc,mul(u,half)),fl=add(fc,mul(u,-half)),sr=add(add(p1,mul(n,depth*.52)),mul(u,len*.08)),sl=add(add(p0,mul(n,depth*.52)),mul(u,-len*.08)),nodes=[p0,p1,sr,fr,fl,sl];return area(nodes)<1000?null:{mode:'one',nodes}}
function med(v){const a=[...v].sort((x,y)=>x-y);return a[Math.floor(a.length/2)]}function stabilize(nodes,m,now){if(mode!==m||!target||target.length!==nodes.length)history=[];mode=m;history.push(nodes.map(x=>({...x})));if(history.length>3)history.shift();let f=nodes;if(history.length>=3)f=nodes.map((_,i)=>({x:med(history.map(q=>q[i].x)),y:med(history.map(q=>q[i].y)),z:0}));if(target&&target.length===f.length)f=f.map((p,i)=>{const d=dist(target[i],p),max=m==='one'?(i<2?70:54):78;return d<=max?p:lerp(target[i],p,max/d)});target=f;lastSeen=now;if(!display||display.length!==f.length)display=f.map(x=>({...x}))}
function updateFromResult(r,now){result=r;const h=(r.landmarks||[]).slice(0,2).map(geom);let p=null;if(h.length>=2){p=twoHand(h);if(p)lastTwo=now}if(!p&&h.length===1&&now-lastTwo>150)p=oneHand(h[0]);if(p)stabilize(p.nodes,p.mode,now)}
function smooth(dt){if(!target)return;if(!display||display.length!==target.length){display=target.map(x=>({...x}));return}display=target.map((p,i)=>{const d=dist(display[i],p),r=d<8?9:d<24?18:d<55?30:44;return lerp(display[i],p,1-Math.exp(-r*dt))})}
function smoothPath(n,tension){const p=new Path2D();if(n.length<3)return p;p.moveTo(n[0].x,n[0].y);for(let i=0;i<n.length;i++){const p0=n[(i-1+n.length)%n.length],p1=n[i],p2=n[(i+1)%n.length],p3=n[(i+2)%n.length],c1={x:p1.x+(p2.x-p0.x)*tension/6,y:p1.y+(p2.y-p0.y)*tension/6},c2={x:p2.x-(p3.x-p1.x)*tension/6,y:p2.y-(p3.y-p1.y)*tension/6};p.bezierCurveTo(c1.x,c1.y,c2.x,c2.y,p2.x,p2.y)}p.closePath();return p}
function filterFrame(now){if(!target||alpha<.02||video.readyState<2||now-filterAt<34)return;filterAt=now;const pr=PRESETS[preset];filterCtx.save();filterCtx.setTransform(1,0,0,1,0,0);filterCtx.clearRect(0,0,filterCanvas.width,filterCanvas.height);filterCtx.filter=pr.css;if(facing==='user'){filterCtx.translate(filterCanvas.width,0);filterCtx.scale(-1,1)}filterCtx.drawImage(video,0,0,filterCanvas.width,filterCanvas.height);filterCtx.restore()}
function drawPortal(n,a,now){if(!n||area(n)<850)return;const pr=PRESETS[preset],path=smoothPath(n,mode==='one'?.78:.48),t=cover(filterCanvas.width,filterCanvas.height,canvas.width,canvas.height);ctx.save();ctx.globalAlpha=a;ctx.clip(path);ctx.drawImage(filterCanvas,t.x,t.y,t.w,t.h);if(pr.scan){const ys=n.map(p=>p.y),lo=Math.min(...ys),hi=Math.max(...ys),y=lo+((now*.00042)%1)*(hi-lo),g=ctx.createLinearGradient(0,y-14,0,y+14);g.addColorStop(0,'rgba(150,245,255,0)');g.addColorStop(.5,'rgba(240,255,255,.18)');g.addColorStop(1,'rgba(150,245,255,0)');ctx.fillStyle=g;ctx.fillRect(0,y-18,canvas.width,36)}if(pr.grid){ctx.globalAlpha=a*.10;ctx.strokeStyle=pr.a;for(let y=0;y<canvas.height;y+=24){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}ctx.restore();if(pr.glitch&&((now/95)|0)%7<2){ctx.save();ctx.globalAlpha=a*.11;ctx.translate(3,-1);ctx.clip(path);ctx.drawImage(filterCanvas,t.x,t.y,t.w,t.h);ctx.restore()}ctx.save();ctx.globalAlpha=a*.22;ctx.lineWidth=8;ctx.strokeStyle=pr.a;ctx.shadowBlur=22;ctx.shadowColor=pr.g;ctx.stroke(path);ctx.restore();ctx.save();ctx.globalAlpha=a*.28;ctx.translate(-1.3,.6);ctx.strokeStyle=pr.b;ctx.lineWidth=2;ctx.stroke(path);ctx.restore();ctx.save();ctx.globalAlpha=a*.96;ctx.strokeStyle='rgba(235,254,255,.98)';ctx.lineWidth=1.35;ctx.stroke(path);ctx.globalAlpha=a*.52;ctx.setLineDash([10,16]);ctx.lineDashOffset=-(now*.038)%26;ctx.strokeStyle=pr.a;ctx.lineWidth=2;ctx.stroke(path);ctx.restore();if(a>.5&&now-particleAt>65&&particles.length<16){particleAt=now;const i=Math.floor(Math.random()*n.length),x=lerp(n[i],n[(i+1)%n.length],Math.random()),c=avg(n),v=norm(sub(x,c));particles.push({x:x.x,y:x.y,vx:v.x*(14+Math.random()*24),vy:v.y*(14+Math.random()*24),born:now,life:280+Math.random()*300})}const dt=Math.min(.05,Math.max(.001,(now-lastRender)/1000)),alive=[];ctx.save();for(const p of particles){const age=now-p.born;if(age>=p.life)continue;p.x+=p.vx*dt;p.y+=p.vy*dt;ctx.globalAlpha=a*(1-age/p.life)*.6;ctx.fillStyle=pr.a;ctx.beginPath();ctx.arc(p.x,p.y,1.2,0,Math.PI*2);ctx.fill();alive.push(p)}ctx.restore();particles=alive;ctx.save();for(let i=0;i<n.length;i++){const primary=mode==='one'&&i<2;ctx.globalAlpha=a*(primary?.95:.55);ctx.fillStyle=primary?'rgba(255,246,120,1)':pr.a;ctx.beginPath();ctx.arc(n[i].x,n[i].y,primary?4:2.3,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawDebug(){if(!debug||!result.landmarks?.length)return;ctx.save();ctx.lineWidth=1.1;ctx.strokeStyle='rgba(255,255,255,.64)';for(const l of result.landmarks){const p=l.map(toScreen);for(const[a,b]of LINKS){ctx.beginPath();ctx.moveTo(p[a].x,p[a].y);ctx.lineTo(p[b].x,p[b].y);ctx.stroke()}for(let i=0;i<p.length;i++){ctx.fillStyle=i===4||i===8?'#fff478':'#5deaff';ctx.beginPath();ctx.arc(p[i].x,p[i].y,i===4||i===8?4:2.2,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function hud(now){const c=result.landmarks?.length||0,fresh=now-lastSeen<280;if(fresh&&mode==='two'){status('PORTAL · 2 TANGAN','ready');hint.classList.remove('visible')}else if(fresh&&mode==='one'){status('PORTAL · CURVE LOCK','ready');hint.classList.remove('visible')}else if(c===1){status('1 TANGAN');hint.innerHTML='Jempol + telunjuk = <b>kontrol utama</b>';hint.classList.add('visible')}else if(c>=2){status('2 TANGAN');hint.innerHTML='Buka <b>jempol + telunjuk</b> di kedua tangan';hint.classList.add('visible')}else{status(`CARI TANGAN · ${backend}`);hint.innerHTML='Tunjukkan <b>satu atau dua tangan</b>';hint.classList.add('visible')}}
function fps(now){fpsN++;if(now-fpsAt>=650){fpsEl.textContent=Math.round(fpsN*1000/(now-fpsAt));fpsN=0;fpsAt=now}}
function drawVideo(c,w,h){const vw=video.videoWidth||1,vh=video.videoHeight||1,t=cover(vw,vh,w,h);c.save();c.setTransform(1,0,0,1,0,0);c.fillStyle='#020305';c.fillRect(0,0,w,h);if(facing==='user'){c.translate(w,0);c.scale(-1,1);c.drawImage(video,w-t.x-t.w,t.y,t.w,t.h)}else c.drawImage(video,t.x,t.y,t.w,t.h);c.restore()}
function recordFrame(now){if(!recording||now-recordAt<33)return;recordAt=now;drawVideo(recordCtx,recordCanvas.width,recordCanvas.height);recordCtx.drawImage(canvas,0,0);const s=Math.floor((now-recordStarted)/1000);recTime.textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function mime(){if(!window.MediaRecorder)return'';for(const t of['video/webm;codecs=vp8','video/webm;codecs=vp9','video/webm'])if(MediaRecorder.isTypeSupported(t))return t;return''}function startRecording(){if(recording)return;if(!window.MediaRecorder||!recordCanvas.captureStream)return pop('Browser belum dukung rekam.');try{recordCanvas.width=canvas.width;recordCanvas.height=canvas.height;drawVideo(recordCtx,recordCanvas.width,recordCanvas.height);recordMime=mime();recordStream=recordCanvas.captureStream(30);chunks=[];recorder=recordMime?new MediaRecorder(recordStream,{mimeType:recordMime,videoBitsPerSecond:4e6}):new MediaRecorder(recordStream,{videoBitsPerSecond:4e6});recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=saveRecording;recorder.start(300);recording=true;recordStarted=performance.now();recordAt=0;recBtn.classList.add('active');recBtn.textContent='■';recBadge.classList.add('visible');recTime.textContent='00:00';pop('Rekam 30 FPS dimulai')}catch(e){console.error(e);pop('Gagal mulai rekam.')}}function stopRecording(){if(!recording)return;recording=false;recBtn.classList.remove('active');recBtn.textContent='●';recBadge.classList.remove('visible');if(recorder&&recorder.state!=='inactive')recorder.stop()}function saveRecording(){try{const b=new Blob(chunks,{type:recordMime||'video/webm'});chunks=[];if(!b.size)return pop('Rekaman kosong.');const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='portal-'+new Date().toISOString().replace(/[:.]/g,'-')+'.webm';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);pop('Rekaman disimpan ✓')}finally{recordStream?.getTracks().forEach(t=>t.stop());recordStream=null;recorder=null}}
function render(now){if(!running)return;const dt=clamp((now-lastRender)/1000,1/240,.05),fresh=now-lastSeen<280;ctx.clearRect(0,0,canvas.width,canvas.height);smooth(dt);alpha+=((fresh?1:0)-alpha)*(1-Math.exp(-(fresh?13:7)*dt));if(!fresh&&alpha<.01)alpha=0;filterFrame(now);if(display&&alpha>0)drawPortal(display,alpha,now);drawDebug();hud(now);fps(now);recordFrame(now);lastRender=now;raf=requestAnimationFrame(render)}
startBtn.addEventListener('click',openCamera);cameraBtn.addEventListener('click',async()=>{if(recording)stopRecording();facing=facing==='user'?'environment':'user';app.dataset.facing=facing;pop(facing==='user'?'Kamera depan':'Kamera belakang');await openCamera()});filterBtn.addEventListener('click',()=>{preset=(preset+1)%PRESETS.length;filterName.textContent=PRESETS[preset].name;filterAt=0;pop(PRESETS[preset].name)});debugBtn.addEventListener('click',()=>{debug=!debug;debugBtn.classList.toggle('active',debug);pop(debug?'Landmark ON · kuning = anchor':'Landmark OFF')});recBtn.addEventListener('click',()=>recording?stopRecording():startRecording());addEventListener('resize',()=>running&&resize());addEventListener('orientationchange',()=>setTimeout(()=>running&&resize(),180));document.addEventListener('visibilitychange',()=>{if(document.hidden){if(recording)stopRecording();stopLoops()}else if(stream){running=true;lastRender=performance.now();raf=requestAnimationFrame(render);startPump()}});initWorker();
